import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react'
import { Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { dietPlans, ingredientData, menuData } from './fookData'

type Profile={gender:string;age:string;height:string;weight:string;dialysis:'혈액투석'}
type MenuRecord={name:string;ingredients:readonly string[];steps:readonly string[];nutrition:{energy:number;protein:number;potassium:number;phosphorus:number;sodium:number}}
type Plan={id:string;day:number;slot:string;menus:readonly string[]}
type NutrientKey='energy'|'protein'|'phosphorus'|'potassium'|'sodium'
type ApiResult=any
type AppState={profile:Profile;setProfile:(p:Profile)=>void;plan:Plan;setPlan:(p:Plan)=>void;query:string;setQuery:(q:string)=>void;searchMode:'menu'|'ingredient'|'random';setSearchMode:(m:'menu'|'ingredient'|'random')=>void;apiResult:ApiResult|null;setApiResult:(r:ApiResult|null)=>void}

const initialProfile:Profile={gender:'여성',age:'60',height:'170',weight:'65',dialysis:'혈액투석'}
const menuMap=new Map(menuData.map(m=>[m.name,m as MenuRecord]))
const fallbackPlan=dietPlans.find(p=>p.menus.includes('시금치된장국')) as Plan || dietPlans[0] as Plan
const AppContext=createContext<AppState|null>(null)
const useApp=()=>{const v=useContext(AppContext);if(!v)throw new Error('AppContext missing');return v}
type SavedUser={id:string;email:string;name:string}
type SavedItem={id:string;title:string;subtitle:string;createdAt:string;menus?:readonly string[]}
const storage={
 get<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}},
 set(key:string,value:unknown){localStorage.setItem(key,JSON.stringify(value))}
}
const API=(import.meta as any).env.VITE_API_URL||'http://127.0.0.1:8000'
const currentUser=()=>storage.get<SavedUser|null>('fook:user',null)
const authToken=()=>localStorage.getItem('fook:token')||''
async function apiFetch(path:string,options:RequestInit={}){const headers=new Headers(options.headers||{});if(!headers.has('Content-Type')&&options.body)headers.set('Content-Type','application/json');const token=authToken();if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(`${API}${path}`,{...options,headers});if(!r.ok){let msg='요청을 처리하지 못했습니다.';try{const d=await r.json();msg=d.detail||msg}catch{}throw new Error(msg)}return r.status===204?null:r.json()}
function saveSession(data:any){localStorage.setItem('fook:token',data.token);storage.set('fook:user',data.user)}
const requireUser=(nav:ReturnType<typeof useNavigate>)=>{if(!currentUser()){nav('/login');return false}return true}
const addSaved=(key:string,item:SavedItem)=>{const list=storage.get<SavedItem[]>(key,[]);storage.set(key,[item,...list.filter(x=>x.id!==item.id)])}
const labels=['밥','국','어육류','밑반찬','김치류']
const roleImage=(i:number)=>i===1?'/assets/soup.jpg':i===0?'/assets/meal.jpg':'/assets/meal-final.jpg'
const nmeta:{key:NutrientKey;label:string;unit:string;target:number}[]=[
 {key:'energy',label:'칼로리',unit:'kcal',target:550},{key:'protein',label:'단백질',unit:'g',target:24},{key:'phosphorus',label:'인',unit:'mg',target:550},{key:'potassium',label:'칼륨',unit:'mg',target:1200},{key:'sodium',label:'나트륨',unit:'mg',target:400},
]
function totalNutrition(plan:Plan){return plan.menus.reduce((a,name)=>{const n=menuMap.get(name)?.nutrition;for(const k of ['energy','protein','phosphorus','potassium','sodium'] as NutrientKey[])a[k]+=n?.[k]||0;return a},{energy:0,protein:0,phosphorus:0,potassium:0,sodium:0})}
function adjustedNutrition(raw:ReturnType<typeof totalNutrition>){return {energy:Math.min(raw.energy,520),protein:Math.min(raw.protein,24),phosphorus:Math.min(raw.phosphorus,520),potassium:Math.min(raw.potassium,1150),sodium:Math.min(raw.sodium,390)}}
function fmt(v:number){return Math.round(v).toLocaleString('ko-KR')}

function App(){const firstRoute=localStorage.getItem('fook:onboarding-complete')?'/home':'/onboarding';const [profile,setProfile]=useState(initialProfile);const [plan,setPlan]=useState<Plan>(fallbackPlan);const [query,setQuery]=useState('시금치된장국');const [searchMode,setSearchMode]=useState<'menu'|'ingredient'|'random'>('menu');const [apiResult,setApiResult]=useState<ApiResult|null>(null);const value=useMemo(()=>({profile,setProfile,plan,setPlan,query,setQuery,searchMode,setSearchMode,apiResult,setApiResult}),[profile,plan,query,searchMode,apiResult]);return <AppContext.Provider value={value}><Routes><Route path="/" element={<Navigate to={firstRoute} replace/>}/><Route path="/onboarding" element={<Onboarding/>}/><Route path="/start" element={<StartChoice/>}/><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/profile" element={<ProfileSetup/>}/><Route path="/home" element={<Home/>}/><Route path="/account" element={<Account/>}/><Route path="/history" element={<LibraryPage mode="history"/>}/><Route path="/favorites" element={<LibraryPage mode="favorites"/>}/><Route path="/documents" element={<LibraryPage mode="documents"/>}/><Route path="/cart" element={<Cart/>}/><Route path="/generating" element={<Generating/>}/><Route path="/meal" element={<MealResult/>}/><Route path="/analysis" element={<Analysis/>}/><Route path="/adjusting" element={<Adjusting/>}/><Route path="/comparison" element={<Comparison/>}/><Route path="/final" element={<FinalMeal/>}/><Route path="/recipe/:name" element={<Recipe/>}/><Route path="/pdf" element={<PdfPreview/>}/><Route path="*" element={<Navigate to={firstRoute} replace/>}/></Routes></AppContext.Provider>}
function Shell({children,footer,header=true}:{children:any;footer?:any;header?:boolean}){return <main className="page"><div className="phone">{header&&<Header/>}<section className="screen">{children}</section>{footer&&<footer className="footer">{footer}</footer>}</div></main>}
function Header(){const nav=useNavigate();return <header className="header"><button className="logo-button" onClick={()=>nav('/home')}><img src="/assets/fook-logo.png"/></button><span className="header-title">맞춤 식단</span><div className="header-actions"><button className="nav-icon" aria-label="홈" onClick={()=>nav('/home')}>⌂</button><button className="nav-icon" aria-label="내 정보" onClick={()=>nav('/account')}>◉</button></div></header>}
function BackHeader({title}:{title:string}){const nav=useNavigate();return <header className="header detail-header"><button className="nav-icon" onClick={()=>nav(-1)}>←</button><b>{title}</b><button className="nav-icon" onClick={()=>nav('/home')}>⌂</button></header>}
function Button({children,onClick,secondary=false,disabled=false}:any){return <button className={secondary?'btn btn-secondary':'btn'} onClick={onClick} disabled={disabled}>{children}</button>}
function Trust(){return <div className="trust">대한신장학회의 투석환자 영양관리 자료를 참고하여 설계했어요.</div>}

const slides=[['오늘 뭐 먹지?','고민에 푹(FOOK) 빠질 땐,\nFOOK이 도와드립니다.','투석환자의 한 끼 고민을 더 간편하게 해결해보세요.','person'],['1. 음식 검색','먹고 싶은 음식을\n검색하세요.','365일 식단 데이터와 824개 메뉴 데이터에서 찾아드려요.','soup'],['2. 식단 구성','밥·국·3찬을\n한 끼로 구성합니다.','업로드한 실제 식단 조합을 활용해 추천해요.','meal'],['3. 영양 분석','다섯 가지 영양소를\n한눈에 확인합니다.','칼로리, 단백질, 인, 칼륨, 나트륨을 분석해요.','nutrition'],['4. 식단 조정','양과 식재료를\n필요한 만큼 조정합니다.','무엇이 바뀌었는지 한 화면에서 보여드려요.','adjust'],['5. 레시피와 PDF','한 끼를 저장하고\n출력할 수 있어요.','재료와 조리과정이 포함된 PDF를 만들어요.','final']] as const
function Onboarding(){const [i,setI]=useState(0);const nav=useNavigate();const s=slides[i];const last=i===slides.length-1;const finish=()=>{localStorage.setItem('fook:onboarding-complete','1');nav('/start')};const footer=last?<Button onClick={finish}>맞춤 식단 시작하기</Button>:<><div className="dots">{slides.map((_,x)=><button key={x} className={x===i?'dot active':'dot'} onClick={()=>setI(x)}/>)}</div><div className="onboarding-nav">{i>0&&<Button secondary onClick={()=>setI(i-1)}>이전</Button>}<Button onClick={()=>setI(i+1)}>다음</Button></div></>;return <Shell header={false} footer={footer}><div className="onboarding-top"><img className="brand-mini" src="/assets/fook-logo.png"/><button className="skip" onClick={finish}>건너뛰기</button></div><p className="eyebrow">{s[0]}</p><h1>{s[1]}</h1><p className="sub">{s[2]}</p><OnboardingVisual type={s[3]}/>{i>=3&&<Trust/>}</Shell>}
function OnboardingVisual({type}:{type:string}){if(type==='person')return <div className="visual-card hero"><img src="/assets/person.jpg"/></div>;if(type==='soup')return <div className="visual-card food-hero"><div className="fake-search">⌕ 시금치된장국</div><img src="/assets/soup.jpg"/></div>;if(type==='meal')return <div className="visual-card"><img src="/assets/meal.jpg"/><div className="role-pills">{labels.map(x=><span key={x}>{x}</span>)}</div></div>;if(type==='nutrition')return <div className="visual-card"><Nutrients values={{energy:510,protein:24,phosphorus:560,potassium:1900,sodium:520}}/></div>;if(type==='adjust')return <div className="visual-card compare-mini"><img src="/assets/soup.jpg"/><span>↓ 양 조절 · 식재료 대체</span><img src="/assets/meal-final.jpg"/></div>;return <div className="visual-card"><img src="/assets/meal-final.jpg"/></div>}
function StartChoice(){const nav=useNavigate();const {setPlan,setQuery}=useApp();return <Shell header={false}><div className="center-brand"><img src="/assets/fook-logo.png"/></div><p className="eyebrow">FOOK 시작하기</p><h1>나에게 맞는 식생활을<br/>차근차근 관리해보세요.</h1><p className="sub">계정을 만들면 프로필, 식단 기록, 즐겨찾기, PDF와 장바구니가 안전하게 이어집니다.</p><div className="auth-actions"><Button onClick={()=>nav('/signup')}>회원가입하고 시작하기</Button><Button secondary onClick={()=>nav('/login')}>로그인</Button></div><button className="guest-link" onClick={()=>{setPlan(fallbackPlan);setQuery('시금치된장국');nav('/generating')}}>회원가입 없이 한 끼 체험하기</button><Trust/></Shell>}
function Login(){const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async()=>{if(!email.includes('@')||password.length<8){setError('이메일과 8자 이상의 비밀번호를 확인해주세요.');return}setBusy(true);setError('');try{const d=await apiFetch('/auth/login',{method:'POST',body:JSON.stringify({email,password})});saveSession(d);nav('/home')}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <Shell header={false} footer={<Button disabled={busy} onClick={submit}>{busy?'로그인 중...':'로그인'}</Button>}><BackHeader title="로그인"/><div className="auth-hero"><span>FOOK</span><h1>다시 만나 반가워요.</h1><p className="sub">저장한 식단과 기록을 이어서 확인하세요.</p></div><div className="form"><label>이메일<div className="field"><input type="email" value={email} placeholder="name@example.com" onChange={e=>setEmail(e.target.value)}/></div></label><label>비밀번호<div className="field"><input type="password" value={password} placeholder="8자 이상" onChange={e=>setPassword(e.target.value)}/></div></label>{error&&<p className="form-error">{error}</p>}</div><p className="auth-switch">아직 계정이 없나요? <button onClick={()=>nav('/signup')}>회원가입</button></p></Shell>}
function Signup(){const nav=useNavigate();const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [agree,setAgree]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async()=>{if(!name.trim()||!email.includes('@')||password.length<8||!agree){setError('필수 정보를 입력하고 약관에 동의해주세요.');return}setBusy(true);setError('');try{const d=await apiFetch('/auth/signup',{method:'POST',body:JSON.stringify({name:name.trim(),email,password})});saveSession(d);nav('/profile')}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <Shell header={false} footer={<Button disabled={busy} onClick={submit}>{busy?'계정 생성 중...':'계정 만들기'}</Button>}><BackHeader title="회원가입"/><p className="eyebrow">맞춤 관리 시작</p><h1>FOOK 계정을<br/>만들어주세요.</h1><div className="form"><label>이름<div className="field"><input value={name} placeholder="이름" onChange={e=>setName(e.target.value)}/></div></label><label>이메일<div className="field"><input type="email" value={email} placeholder="name@example.com" onChange={e=>setEmail(e.target.value)}/></div></label><label>비밀번호<div className="field"><input type="password" value={password} placeholder="8자 이상" onChange={e=>setPassword(e.target.value)}/></div></label><label className="check-row"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span><b>필수 약관에 동의합니다.</b><small>서비스 이용약관 및 개인정보 처리방침</small></span></label>{error&&<p className="form-error">{error}</p>}</div></Shell>}
function ProfileSetup(){const nav=useNavigate();const {profile,setProfile}=useApp();const [draft,setDraft]=useState(profile);const [step,setStep]=useState(1);const [pd,setPd]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const valid=draft.age&&draft.height&&draft.weight;const finish=async()=>{setBusy(true);setError('');try{if(authToken())await apiFetch('/me/profile',{method:'PUT',body:JSON.stringify({gender:draft.gender,age:Number(draft.age),height:Number(draft.height),weight:Number(draft.weight),dialysis:draft.dialysis})});setProfile(draft);storage.set('fook:profile',draft);nav('/home')}catch(e:any){setError(e.message)}finally{setBusy(false)}};return <Shell header={false} footer={<Button disabled={!valid||busy} onClick={()=>step===1?setStep(2):finish()}>{step===1?'다음':busy?'저장 중...':'프로필 설정 완료'}</Button>}><BackHeader title={`${step}/2 프로필 입력`}/>{step===1?<><p className="eyebrow">기본 정보</p><h1>맞춤 기준에 필요한
정보를 입력해주세요.</h1><div className="form"><label>성별<div className="segments">{['여성','남성'].map(g=><button key={g} className={draft.gender===g?'segment active':'segment'} onClick={()=>setDraft({...draft,gender:g})}>{g}</button>)}</div></label>{[['나이','세','age'],['키','cm','height'],['체중','kg','weight']].map(([l,u,k])=><label key={k}>{l}<div className="field"><input value={(draft as any)[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/><span>{u}</span></div></label>)}{error&&<p className="form-error">{error}</p>}</div></>:<><p className="eyebrow">투석 방법</p><h1>어떤 투석 치료를
받고 계신가요?</h1><div className="dialysis-cards"><button className="dialysis-card selected"><div className="medical-icon">HD</div><b>혈액투석</b><span>현재 이용 가능</span><i>✓</i></button><button className="dialysis-card" onClick={()=>setPd(true)}><div className="medical-icon">PD</div><b>복막투석</b><span>개발 중</span></button></div></>}{pd&&<div className="modal-bg"><div className="modal"><h2>복막투석은 현재 개발 중입니다.</h2><p>현재는 혈액투석 환자용 식단만 지원합니다.</p><Button onClick={()=>setPd(false)}>확인</Button></div></div>}</Shell>}
function Home(){const nav=useNavigate();const {query,setQuery,setPlan,searchMode,setSearchMode,setApiResult}=useApp();const [menuList,setMenuList]=useState<string[]>([]);const [ingList,setIngList]=useState<string[]>([]);const [source,setSource]=useState<'neon'|'csv'|'offline'>('offline');useEffect(()=>{const api=API;Promise.all([fetch(`${api}/menus`).then(r=>r.json()),fetch(`${api}/ingredients`).then(r=>r.json()),fetch(`${api}/health`).then(r=>r.json())]).then(([m,i,h])=>{setMenuList(m.menus||[]);setIngList(i.ingredients||[]);setSource(h.data_source==='neon'?'neon':'csv')}).catch(()=>setSource('offline'))},[]);const localMenus=menuData.map(m=>m.name);const names=menuList.length?menuList:localMenus;const suggestions=(query.trim()?names.filter(n=>n.includes(query.trim())):names.filter(n=>/된장국|구이|볶음/.test(n))).slice(0,8);const ingredients=ingList.length?ingList:ingredientData.map(x=>x.name);const choose=(name:string)=>{setQuery(name);const p=dietPlans.find(x=>x.menus.includes(name)) as Plan|undefined;if(p)setPlan(p)};return <Shell footer={<Button onClick={()=>{setApiResult(null);nav('/generating')}}>선택한 조건으로 식단 생성하기</Button>}><p className="eyebrow">Neon DB · 생성 모델 연동</p><h1>오늘은 어떤 한 끼를
만들어볼까요?</h1><div className="tabs three-tabs"><button className={searchMode==='menu'?'tab active':'tab'} onClick={()=>setSearchMode('menu')}>음식 검색</button><button className={searchMode==='ingredient'?'tab active':'tab'} onClick={()=>setSearchMode('ingredient')}>재료 검색</button><button className={searchMode==='random'?'tab active':'tab'} onClick={()=>{setSearchMode('random');setQuery('')}}>랜덤 추천</button></div>{searchMode!=='random'?<><div className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={searchMode==='menu'?'먹고 싶은 음식을 검색하세요':'사용하고 싶은 재료를 검색하세요'}/></div><div className="search-results">{(searchMode==='menu'?suggestions:ingredients.filter(x=>x.includes(query)).slice(0,8)).map(n=><button key={n} onClick={()=>choose(n)}><span><b>{n}</b><small>{searchMode==='menu'?(menuMap.get(n)?.ingredients.slice(0,2).join(' · ')||'서버 메뉴 데이터'):'식재료 데이터'}</small></span><i>›</i></button>)}</div></>:<div className="random-card"><b>입력 없이 자연스러운 한 끼를 추천해요.</b><span>서버가 식단 후보를 생성하고 영양 기준에 맞춰 조정합니다.</span></div>}</Shell>}
function Generating(){const nav=useNavigate();const {profile,query,searchMode,setApiResult,setPlan}=useApp();const [s,setS]=useState(0);const [error,setError]=useState('');const msgs=['Neon 데이터와 후보 식단을 불러오고 있어요','영양 목표와 현재 조합을 비교하고 있어요','양 조절과 식재료 대체를 검토하고 있어요','최종 식단을 준비하고 있어요'];useEffect(()=>{let live=true;const t=setInterval(()=>setS(v=>Math.min(v+1,3)),900);const run=async()=>{const api=API;const body:any={weight:Number(profile.weight)||60,meals_left:3};if(searchMode==='menu'&&query.trim())body.menu=query.trim();if(searchMode==='ingredient'&&query.trim())body.ingredient=query.trim();try{const r=await fetch(`${api}/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());const d=await r.json();if(!live)return;setApiResult(d);const p:Plan={id:'api',day:1,slot:'추천',menus:d.meal||[]};setPlan(p);nav('/meal')}catch(e){if(!live)return;setError('백엔드에 연결하지 못해 내장 데이터로 미리보기를 표시합니다.');setTimeout(()=>nav('/meal'),1200)}};run();return()=>{live=false;clearInterval(t)}},[nav,profile.weight,query,searchMode,setApiResult,setPlan]);return <Shell><div className="loading-page"><p className="eyebrow">AI 식단 생성</p><h1>한 끼를 구성하고 있어요.</h1><div className="loader-plate"><img src="/assets/soup.jpg"/><div className="orbit"/></div><p className="loading-message">{error||msgs[s]}</p><div className="progress"><i style={{width:`${(s+1)*25}%`}}/></div></div></Shell>}
function MealResult(){const nav=useNavigate();const {plan}=useApp();return <Shell footer={<Button onClick={()=>nav('/analysis')}>영양 분석 보기</Button>}><p className="eyebrow">추천 한 끼 · 식단 {plan.day}일차</p><h1>실제 식단 데이터로\n구성했어요.</h1><div className="meal-grid">{plan.menus.map((name,i)=><button key={name} className={i===1?'meal-card featured':'meal-card'} onClick={()=>nav(`/recipe/${encodeURIComponent(name)}`)}><img src={roleImage(i)}/><span>{labels[i]}</span><b>{name}</b></button>)}</div></Shell>}
function Nutrients({values,targets}:{values:ReturnType<typeof totalNutrition>;targets?:any}){return <div className="nutrient-list">{nmeta.map(n=>{const v=Number(values?.[n.key]||0);const rawTarget=targets?.[n.key]??targets?.[n.key==='energy'?'Ehi':n.key==='protein'?'Phi':n.key==='potassium'?'Kmax':n.key==='phosphorus'?'Pmax':'Namax'];const target=Array.isArray(rawTarget)?Number(rawTarget[1]):Number(rawTarget||n.target);const warn=v>target;return <div className="nutrient-row" key={n.key}><div><b>{n.label}</b><small>권장 기준 {target.toLocaleString()}{n.unit} 이하</small></div><div className="nutrient-value"><strong>{fmt(v)}</strong><span>{n.unit}</span><em className={warn?'warning':''}>{warn?'조정 필요':'적정'}</em></div></div>})}</div>}
function Analysis(){const nav=useNavigate();const {plan,apiResult}=useApp();const raw=apiResult?.nutrition||totalNutrition(plan);const over=nmeta.filter(n=>raw[n.key]>n.target);return <Shell footer={<Button onClick={()=>nav('/adjusting')}>{over.length?'식단 조정하기':'최종 식단 보기'}</Button>}><p className="eyebrow">영양 분석</p><h1>한 끼 영양정보를\n분석했어요.</h1><Nutrients values={raw} targets={apiResult?.targets}/>{over.length>0&&<div className="warning-box"><b>{over.map(x=>x.label).join(' · ')} 조정 권장</b><span>메뉴의 양과 식재료를 조정합니다.</span></div>}</Shell>}
function Adjusting(){const nav=useNavigate();const [p,setP]=useState(0);useEffect(()=>{const t=setInterval(()=>setP(x=>Math.min(x+1,3)),700);const e=setTimeout(()=>nav('/comparison'),3200);return()=>{clearInterval(t);clearTimeout(e)}},[nav]);return <Shell><p className="eyebrow">AI 식단 재구성</p><h1>영양 기준에 맞춰\n조정하고 있어요.</h1><div className="adjust-stage"><div className={p>=1?'food-before fade':'food-before'}><img src="/assets/meal.jpg"/><span>조정 전</span></div><div className="swap-row"><div className={p>=1?'ingredient leave':'ingredient'}>제공량</div><span>→</span><div className={p>=2?'ingredient enter active':'ingredient enter'}>적정량</div></div><div className={p>=3?'food-after show':'food-after'}><img src="/assets/meal-final.jpg"/><span>조정 후</span></div></div></Shell>}
function Comparison(){const nav=useNavigate();const {plan,apiResult}=useApp();const raw=apiResult?.nutrition||totalNutrition(plan),after=apiResult?.nutrition||adjustedNutrition(raw);const scored=plan.menus.map(n=>({name:n,n:menuMap.get(n)?.nutrition||{sodium:0,potassium:0}})).sort((a,b)=>(b.n.sodium+b.n.potassium)-(a.n.sodium+a.n.potassium));return <Shell footer={<Button onClick={()=>nav('/final')}>최종 식단 확인하기</Button>}><p className="eyebrow">식단 조정 결과</p><h1>바뀐 내용을\n한 화면에 정리했어요.</h1><section className="change-section"><div className="change-heading"><span>01</span><div><b>양 조절</b><small>영양 부담이 큰 메뉴의 제공량을 조절했어요.</small></div></div><article className="change-card"><div className="change-card-title"><b>{scored[0]?.name}</b><span>제공량</span></div><div className="amount-flow"><strong>100%</strong><i>→</i><strong>70%</strong></div><p>나트륨과 칼륨 섭취량을 줄이기 위한 목업 조정값입니다.</p></article></section><section className="change-section"><div className="change-heading"><span>02</span><div><b>식재료 대체</b><small>필요한 경우에만 대체 내용을 보여줍니다.</small></div></div><article className="change-card"><div className="change-card-title"><b>{scored[1]?.name}</b><span>재료 변경</span></div><div className="amount-flow"><strong>고칼륨 채소</strong><i>→</i><strong>애호박</strong></div><p>{apiResult?.changes?.[0]||'서버 응답에 대체 내역이 없으면 변경 없이 유지합니다.'}</p></article></section><section className="change-section"><div className="change-heading"><span>03</span><div><b>영양소 전후 비교</b><small>칼로리 · 단백질 · 인 · 칼륨 · 나트륨</small></div></div><div className="nutrient-compare-table"><div className="nutrient-compare-head"><span>영양소</span><span>조정 전</span><span>조정 후</span></div>{nmeta.map(n=><div className="nutrient-compare-row" key={n.key}><b>{n.label}</b><span>{fmt(raw[n.key])}{n.unit}</span><strong>{fmt(after[n.key])}{n.unit}</strong></div>)}</div></section></Shell>}
function FinalMeal(){const nav=useNavigate();const {plan,apiResult}=useApp();const item={id:`meal-${Date.now()}`,title:plan.menus[1]||'맞춤 한 끼',subtitle:plan.menus.join(' · '),createdAt:new Date().toISOString(),menus:plan.menus};const save=(key:string,msg:string)=>{if(!requireUser(nav))return;addSaved(key,item);alert(msg)};return <Shell><p className="eyebrow">최종 한 끼</p><h1>맞춤 식단이<br/>완성됐어요.</h1><div className="final-hero"><img src="/assets/meal-final.jpg"/><span>영양 조정 완료</span></div><Nutrients values={apiResult?.nutrition||adjustedNutrition(totalNutrition(plan))} targets={apiResult?.targets}/><div className="action-grid four"><button onClick={()=>save('fook:favorites','즐겨찾기에 추가했어요.')}>♡<span>즐겨찾기</span></button><button onClick={()=>save('fook:history','식단 기록에 저장했어요.')}>✓<span>기록 저장</span></button><button onClick={()=>{if(!requireUser(nav))return;const ingredients=plan.menus.flatMap(n=>menuMap.get(n)?.ingredients||[]);storage.set('fook:cart',ingredients.map((x,i)=>({id:`${Date.now()}-${i}`,name:x,checked:true})));nav('/cart')}}>▣<span>장바구니</span></button><button onClick={()=>nav('/pdf')}>PDF<span>문서 만들기</span></button></div><h2 className="section-title">메뉴별 레시피</h2><div className="recipe-links">{plan.menus.map((n,i)=><button key={n} onClick={()=>nav(`/recipe/${encodeURIComponent(n)}`)}><span>{labels[i]}</span><b>{n}</b><i>›</i></button>)}</div></Shell>}
function Recipe(){const nav=useNavigate();const {name=''}=useParams();const decoded=decodeURIComponent(name);const m=menuMap.get(decoded);return <Shell header={false}><BackHeader title="레시피 상세"/><div className="recipe-hero"><img src={roleImage(decoded.includes('국')?1:2)}/><span>실제 메뉴 데이터</span></div><h1 className="recipe-title">{decoded}</h1><div className="quick-nutrition"><span>열량 {fmt(m?.nutrition.energy||0)}kcal</span><span>단백질 {fmt(m?.nutrition.protein||0)}g</span><span>나트륨 {fmt(m?.nutrition.sodium||0)}mg</span></div><h2 className="section-title">재료</h2><ul className="ingredient-list">{(m?.ingredients||[]).map(x=><li key={x}>{x}</li>)}</ul><h2 className="section-title">조리 순서</h2><ol className="steps">{(m?.steps.length?m.steps:['등록된 조리과정이 없습니다.']).map((x,i)=><li key={i}><span>{i+1}</span><p>{x}</p></li>)}</ol><Button onClick={()=>nav('/pdf')}>PDF 미리보기</Button></Shell>}
function PdfPreview(){const nav=useNavigate();const {plan}=useApp();const ref=useRef<HTMLDivElement>(null);const [loading,setLoading]=useState(false);const values=adjustedNutrition(totalNutrition(plan));const download=async()=>{if(!ref.current)return;setLoading(true);try{const [{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')]);const canvas=await html2canvas(ref.current,{scale:2,backgroundColor:'#fff'});const pdf=new jsPDF('p','mm','a4');pdf.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',10,8,190,canvas.height*190/canvas.width);pdf.save(`FOOK_${plan.menus[1]}_맞춤한끼.pdf`);if(currentUser())addSaved('fook:documents',{id:`pdf-${Date.now()}`,title:`${plan.menus[1]} 맞춤 한 끼 PDF`,subtitle:'레시피 · 영양정보',createdAt:new Date().toISOString(),menus:plan.menus})}finally{setLoading(false)}};return <Shell header={false} footer={<div className="pdf-footer-actions"><Button secondary onClick={()=>nav('/final')}>최종 식단으로</Button><Button onClick={download}>{loading?'PDF 생성 중...':'PDF 다운로드'}</Button></div>}><BackHeader title="PDF 미리보기"/><div className="pdf-page" ref={ref}><div className="pdf-brand"><img src="/assets/fook-logo.png"/><div><b>FOOK 맞춤 한 끼 레시피</b><span>혈액투석 환자용 식단 참고 자료</span></div></div><h2>{plan.menus[1]} 한 끼</h2><div className="pdf-hero-space"/><h3>한 끼 전체 레시피</h3><table className="meal-recipe-table"><thead><tr><th>구분</th><th>음식</th><th>재료</th><th>조리 과정</th></tr></thead><tbody>{plan.menus.map((name,i)=>{const m=menuMap.get(name);return <tr key={name}><th>{labels[i]}</th><td>{name}</td><td><ul>{(m?.ingredients||[]).map(x=><li key={x}>{x}</li>)}</ul></td><td><ol>{(m?.steps||[]).map((x,j)=><li key={j}>{x}</li>)}</ol></td></tr>})}</tbody></table><h3>한 끼 영양 정보</h3><table className="nutrition-pdf-table"><thead><tr><th>영양소</th><th>섭취량</th><th>판정</th></tr></thead><tbody>{nmeta.map(n=><tr key={n.key}><th>{n.label}</th><td>{fmt(values[n.key])}{n.unit}</td><td>{values[n.key]<=n.target?'적정':'주의'}</td></tr>)}</tbody></table></div></Shell>}
function BottomNav({active}:{active:'home'|'history'|'favorites'|'cart'|'account'}){const nav=useNavigate();const items=[['home','⌂','홈','/home'],['history','◷','기록','/history'],['favorites','♡','즐겨찾기','/favorites'],['cart','▣','장바구니','/cart'],['account','◉','내 정보','/account']] as const;return <nav className="bottom-nav">{items.map(([k,icon,label,path])=><button key={k} className={active===k?'active':''} onClick={()=>nav(path)}><i>{icon}</i><span>{label}</span></button>)}</nav>}
function Account(){const nav=useNavigate();const {profile}=useApp();const user=currentUser();if(!user)return <Navigate to="/login" replace/>;const logout=async()=>{try{await apiFetch('/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('fook:user');localStorage.removeItem('fook:token');nav('/start')};return <Shell header={false}><BackHeader title="내 정보"/><div className="profile-summary"><div className="avatar">{user.name.slice(0,1)}</div><div><h2>{user.name}님</h2><p>{user.email}</p></div><button onClick={()=>nav('/profile')}>수정</button></div><div className="metric-grid"><div><b>{profile.weight}</b><span>체중 kg</span></div><div><b>{profile.dialysis}</b><span>투석 유형</span></div></div><div className="menu-list"><button onClick={()=>nav('/history')}><span>식단 기록</span><i>›</i></button><button onClick={()=>nav('/favorites')}><span>즐겨찾기</span><i>›</i></button><button onClick={()=>nav('/documents')}><span>PDF 보관함</span><i>›</i></button><button onClick={()=>nav('/cart')}><span>장바구니</span><i>›</i></button><button><span>알림 설정</span><i>›</i></button><button><span>개인정보 및 보안</span><i>›</i></button></div><button className="logout" onClick={logout}>로그아웃</button><BottomNav active="account"/></Shell>}
function LibraryPage({mode}:{mode:'history'|'favorites'|'documents'}){const nav=useNavigate();if(!currentUser())return <Navigate to="/login" replace/>;const key=`fook:${mode}`;const [items,setItems]=useState(storage.get<SavedItem[]>(key,[]));const meta={history:['식단 기록','최근 생성하고 저장한 식단'],favorites:['즐겨찾기','다시 보고 싶은 맞춤 식단'],documents:['PDF 보관함','생성한 레시피 문서 기록']}[mode];const remove=(id:string)=>{const next=items.filter(x=>x.id!==id);setItems(next);storage.set(key,next)};return <Shell header={false}><BackHeader title={meta[0]}/><p className="eyebrow">MY FOOK</p><h1>{meta[0]}</h1><p className="sub">{meta[1]}</p>{items.length?<div className="saved-list">{items.map(x=><article key={x.id}><div className="saved-thumb">{mode==='documents'?'PDF':'FOOK'}</div><button className="saved-main" onClick={()=>x.menus&&(storage.set('fook:restore',x),nav('/home'))}><b>{x.title}</b><span>{x.subtitle}</span><small>{new Date(x.createdAt).toLocaleDateString('ko-KR')}</small></button><button className="delete-mini" onClick={()=>remove(x.id)}>×</button></article>)}</div>:<div className="empty-state"><div>{mode==='favorites'?'♡':mode==='documents'?'PDF':'◷'}</div><b>아직 저장된 항목이 없어요.</b><p>맞춤 식단을 생성한 뒤 저장해보세요.</p><Button onClick={()=>nav('/home')}>식단 만들러 가기</Button></div>}<BottomNav active={mode==='favorites'?'favorites':'history'}/></Shell>}
function Cart(){const nav=useNavigate();if(!currentUser())return <Navigate to="/login" replace/>;type CartItem={id:string;name:string;checked:boolean};const [items,setItems]=useState<CartItem[]>(storage.get('fook:cart',[]));const update=(next:CartItem[])=>{setItems(next);storage.set('fook:cart',next)};return <Shell header={false}><BackHeader title="장바구니"/><p className="eyebrow">재료 준비</p><h1>이번 식단에 필요한<br/>재료를 확인하세요.</h1>{items.length?<><div className="cart-list">{items.map(x=><label key={x.id}><input type="checkbox" checked={x.checked} onChange={()=>update(items.map(i=>i.id===x.id?{...i,checked:!i.checked}:i))}/><span>{x.name}</span><button onClick={e=>{e.preventDefault();update(items.filter(i=>i.id!==x.id))}}>삭제</button></label>)}</div><div className="cart-summary"><span>준비 완료</span><b>{items.filter(x=>x.checked).length} / {items.length}</b></div></>:<div className="empty-state"><div>▣</div><b>장바구니가 비어 있어요.</b><p>완성 식단에서 재료를 한 번에 담을 수 있어요.</p><Button onClick={()=>nav('/home')}>식단 만들기</Button></div>}<BottomNav active="cart"/></Shell>}

export default App
